Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Authorization;
using MovieRentalAppProject.Models;
using MovieRentalAppProject.Services;

namespace MovieRentalAppProject.Controllers
{
    
    public class AdminController : Controller
    {

        private readonly IMovieServices _movieServices;
        private readonly IBookingServices _bookingsServices;

        public AdminController(IMovieServices movieServices , IBookingServices bookingServices)
        {
            
            _movieServices = movieServices;
            _bookingsServices = bookingServices;
            

        }

        public IActionResult GetAllBookings()
        {
            List<BookingModel> bookings = _bookingsServices.GetAllBookings();
            return View(bookings);
        }

        
        public IActionResult Allmovies()
        {
            HttpContext.Session.GetString("UserName");
            List<MovieModel> allMovies = _movieServices.GetAllMovies();
            return View(allMovies);
        }


        [HttpGet]
        public IActionResult AddMovies()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddMovies(MovieModel movie ,IFormFile imageFile)
        {
            if(imageFile != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    imageFile.CopyTo(memoryStream);
                    movie.ImageData = memoryStream.ToArray();
                }
            }

            bool addMovies = _movieServices.AddMovies(movie);
            return RedirectToAction("Allmovies");
            
        }
       

        


        [HttpGet]
        public IActionResult UpdateMovies(int id)
        {
            MovieModel movie = _movieServices.GetMovieById(id);
            if(movie == null )
            {
                return NotFound();
            }
            return View(movie);
        }

        [HttpPost]
        public IActionResult UpdateMovies(MovieModel movie , IFormFile imageFile)
        {
            
            if (movie != null && imageFile != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    imageFile.CopyTo(memoryStream);
                    movie.ImageData = memoryStream.ToArray();
                }
                bool updateMovie = _movieServices.UpdateMovies(movie);
                return RedirectToAction("Allmovies");
            }
            else
            {
                ModelState.AddModelError("", "Movie Not Found");
            }

            return View(movie);
        }

        [HttpGet]
       /* public IActionResult GetMoviesByCategory(int categoryId)
        {
            return View();
        }*/

        [HttpGet]
        public IActionResult DeleteMovies(int id)
        {
            MovieModel movie = _movieServices.GetMovieById(id);
            if(movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }


        [HttpPost]
        public IActionResult DeletedMovies(int id)
        {
            bool deletedMovie = _movieServices.DeletedMovies(id);
            if (deletedMovie)
            {
                return RedirectToAction("Allmovies");
            }
            else
            {
                return NotFound();
            }

            
        }


        [HttpGet]
        public IActionResult Bookings(int id)
        { 
            List<BookingModel> bookings = _movieServices.GetAllBookingsForMovie(id);
            return View(bookings);
        }

        [HttpGet]
        public IActionResult GetUserBookingsDetails(int id )
        {
            UserModel user = _movieServices.GetUserWithMovie(id);
           // MovieModel movie = _movieServices.GetMovieById();


                return View(user);
        }

        [HttpDelete]
        public IActionResult DeleteBookingForUser(int uid, int bid)
        {
            bool delete = _movieServices.DeleteBookingForUser(uid, bid);

            if (delete)
            {
                return RedirectToAction("GetAllBookings");
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult DeleteBookings(int id)
        {
            BookingModel booking = _bookingsServices.GetBookingById(id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        [HttpPost]
        public IActionResult DeleteConfirmedBooking(BookingModel model)
        {
            _bookingsServices.DeleteBooking(model.bookingId);
            return RedirectToAction("Allmovies");
        }




    }
}

Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieRentalAppProject.Models;
using MovieRentalAppProject.Services;

namespace MovieRentalAppProject.Controllers
{
    
    public class BookingController : Controller
    {
        private readonly IBookingServices _bookingService;
        private readonly IMovieServices _movieService;
        public BookingController(IBookingServices bookingService , IMovieServices movieServices)
        {
            _bookingService = bookingService;
            _movieService = movieServices;
        }

        public IActionResult MovieDetails(int id)
        {
            MovieModel movie = _movieService.GetMovieById(id);

            return View(movie);
        }

        [HttpGet]
        public IActionResult AddBookings(int id)
        {
            BookingModel booking = new BookingModel();

            booking.bookingTime = DateTime.Now;
            booking.movieId = id;
            booking.userId =(int)HttpContext.Session.GetInt32("UserId");

            return View(booking);
        }
        
        [HttpPost]
        public IActionResult AddBookings(BookingModel booking)
        {

            
                _bookingService.AddBooking(booking);
            return RedirectToAction("AllmoviesUser","User");
            


           
        }

        [HttpGet]
        public IActionResult EditBookings(int id)
        {
            BookingModel booking = _bookingService.GetBookingById(id);
            if (booking == null)
            {
                return NotFound();
            }

           
            return View(booking);
        }

        [HttpPost]
        public IActionResult EditBookings(BookingModel booking)
        {
            if (ModelState.IsValid)
            {
                _bookingService.UpdateBooking(booking);
                return RedirectToAction("Index");
            }

           
            return View(booking);
        }

        [HttpGet]
        public IActionResult DeleteBookings(int id)
        {
            BookingModel booking = _bookingService.GetBookingById(id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        [HttpPost]
        public IActionResult DeleteConfirmedBooking(BookingModel model)
        {
            _bookingService.DeleteBooking(model.bookingId);
            return RedirectToAction("Allmovies");
        }


    }
}

Views/Booking/AddBookings.cshtml
@model MovieRentalAppProject.Models.BookingModel

@{
    ViewData["Title"] = "AddBookings";
}
<br />
<header>
    @Html.Partial("NavBarPartialViewUser")
</header>
<br />


<h1>Confirm Booking</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @*<div>
            <p>Current Date and Time: @DateTime.Now</p>
            <p>Movie Name: @Model.movieId</p>
            <p>User ID: @Context.Session.GetString("UserID")</p>
        </div>*@
        <form asp-action="AddBookings" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <p> <h3>Your Booking for this movie will be confirmed .</h3> 
                    <h4>Please Confrim below</h4>
                </p>
            </div>


            <div class="form-group">
                @*<label asp-for="bookingTime" class="control-label"></label>*@
                <input type="hidden" asp-for="bookingTime" class="form-control" />
                <span asp-validation-for="bookingTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="userId" class="control-label"></label>*@
                <input type="hidden" asp-for="userId" class="form-control" asp-items="ViewBag.userId"></input>
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="movieId" class="control-label"></label>*@
                <input type="hidden" asp-for="movieId" class="form-control" asp-items="ViewBag.movieId"></input>
                <span asp-validation-for="movieId" class="text-danger"></span>
            </div>



          @* <div class="form-group">
                <label asp-for="bookingTime" class="control-label"></label>
                <input type="hidden" asp-for="bookingTime" class="form-control" value="@DateTime.Now" />
                
            </div>
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <input type="hidden" asp-for="userId" class ="form-control" value="@Context.Session.GetString("UserId")" />
            </div>
            <div class="form-group">
                <label asp-for="movieId" class="control-label"></label>
                <input type="hidden" asp-for="movieId" value="@Model.movieId" class="form-control" />
               
            </div>*@


            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-primary" />
                <a class="btn btn-danger" asp-controller="User" asp-action="GetMoviesBookedByUser" asp-route-id="@Model.userId">Cancel</a>
            </div>
        </form>
    </div>
</div>


<br />
<footer>
    @Html.Partial("FooterView")
</footer>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Booking/DeleteBookings.cshtml
@model MovieRentalAppProject.Models.BookingModel

@{
    ViewData["Title"] = "DeleteBookings";
}
<br />

<header>
    @Html.Partial("NavBarPartialViewAdmin")
</header>

<h3>Delete Booking </h3>

<h4>Are you sure you want to delete this?</h4>
<div>
    <h5>Booking</h5>
    <hr />
    <form asp-action="DeleteConfirmedBooking" asp-controller="Admin" method="post">
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bookingTime)
        </dt>*@
        <dd class = "col-sm-10" style="display:none;">
            @Html.DisplayFor(model => model.bookingTime)
        </dd>
       @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.user)
        </dt>*@
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.user.confirmPassword)
        </dd>
       @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.movie)
        </dt>*@
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.movie.movieId)
        </dd>
    </dl>
    
    
        <input type="hidden" asp-for="bookingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        </form>
</div>


<br />
<footer>
    @Html.Partial("FooterView")
</footer>

Views/Booking/EditBookings.cshtml
@model MovieRentalAppProject.Models.BookingModel

@{
    ViewData["Title"] = "EditBookings";
}

<h1>EditBookings</h1>

<h4>BookingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBookings">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="bookingId" />
            <div class="form-group">
                <label asp-for="bookingTime" class="control-label"></label>
                <input asp-for="bookingTime" class="form-control" />
                <span asp-validation-for="bookingTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <select asp-for="userId" class="form-control" asp-items="ViewBag.userId"></select>
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="movieId" class="control-label"></label>
                <select asp-for="movieId" class="form-control" asp-items="ViewBag.movieId"></select>
                <span asp-validation-for="movieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Booking/MovieDetails.cshtml
@model MovieRentalAppProject.Models.MovieModel

@{
    ViewData["Title"] = "Movie Details";
}

<h1>Movie Details</h1>
<br />

<header>
    @Html.Partial("NavBarPartialViewUser")
</header>
<br />

@*@if (TempData["ShowAlert"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["ShowAlert"]
    </div>
}*@

<div class="card mb-4">
    <img src="data:image/png;base64,@Convert.ToBase64String(Model.ImageData)" class="card-img-top" alt="@Model.movieId">
    <div class="card-body">
        
        <h5 class="card-title"><strong>Name : </strong>@Model.movieName</h5>
        <p class="card-text"><strong>Category : </strong>@Model.movieCategory</p>
        <p class="card-text"><strong>Price : </strong> @Model.rentPrice</p>
        <p class="card-text"><strong>Director : </strong> @Model.director</p>
        <p class="card-text"><strong>Actor : </strong> @Model.actors</p>

       @* @if (TempData["ShowAlert"] == null)
        {*@
            <a class="btn btn-warning" asp-controller="Booking" asp-action="AddBookings" asp-route-id="@Model.movieId">Buy Now</a>
        
        @*<a class="btn btn-warning" asp-controller="Booking" asp-action="AddBookings" asp-route-id="@Model.movieId">Buy Now</a>*@
      @*  <a class="btn btn-danger" asp-action="Allmoview" asp-route-id="@Model.movieId">Cancel</a>*@
        <a class="btn btn-secondary" asp-controller="User" asp-action="AllmoviesUser">Back to All Movies</a>
        
    </div>
</div>


<br />
<footer>
    @Html.Partial("FooterView")
</footer>







@*@model MovieRentalAppProject.Models.MovieModel

@{
    ViewData["Title"] = "MovieDetails";
}

<h1>MovieDetails</h1>

<div>
    <h4>MovieModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.movieName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.movieName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.movieCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.movieCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rentPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rentPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.actors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.actors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageData)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.movieId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
*@